from pydantic import BaseModel

from src.contracts.artifact_contracts import SizeScore


class BaseModelRating(BaseModel):
    """Model rating summary generated by the evaluation service."""
    name: str
    category: str
    net_score: float
    net_score_latency: float
    ramp_up_time: float
    ramp_up_time_latency: float
    bus_factor: float
    bus_factor_latency: float
    performance_claims: float
    performance_claims_latency: float
    license: float
    license_latency: float
    dataset_and_code_score: float
    dataset_and_code_score_latency: float
    dataset_quality: float
    dataset_quality_latency: float
    code_quality: float
    code_quality_latency: float
    reproducibility: float
    reproducibility_latency: float
    reviewedness: float
    reviewedness_latency: float
    tree_score: float
    tree_score_latency: float
    size_score: SizeScore
    size_score_latency: float

    @staticmethod
    def to_base(other: "BaseModelRating") -> "BaseModelRating":
        return BaseModelRating(
            **other.__dict__
        )